// <auto-generated />
namespace ClothResorting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Deleted3PropertiesOfPreReceiveOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Deleted3PropertiesOfPreReceiveOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201807111713367_Deleted3PropertiesOfPreReceiveOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
